// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<Result<HealthInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAccounts() : Promise<Result<Account[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns existing account matching `ofx_acctid` if any, otherwise creates one.
 * `kind` is preserved when the account already exists.
 */
async createOrGetAccount(input: NewAccount) : Promise<Result<Account, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_or_get_account", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategories() : Promise<Result<Category[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategoriesWithCount() : Promise<Result<CategoryWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories_with_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCategory(input: NewCategory) : Promise<Result<Category, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_category", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCategory(categoryId: number, input: UpdateCategory) : Promise<Result<Category, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { categoryId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a category. Transactions referencing it get category_id=NULL.
 */
async deleteCategory(categoryId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTransactions(filters: TransactionFilters | null) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_transactions", { filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert a batch of new transactions. Returns counts of inserted vs skipped (duplicates).
 * Dedup happens via UNIQUE(account_id, ofx_fitid, date, amount) + INSERT OR IGNORE.
 * The triple matches genuinely identical transactions — the same FITID with a
 * different amount or date (typical Nubank case: original purchase plus
 * refund) is stored as a distinct tx.
 */
async insertTransactions(accountId: number, txs: NewTransaction[]) : Promise<Result<InsertResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_transactions", { accountId, txs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Given `(fitid, date, amount)` triples, returns the subset already present in
 * this account. The frontend uses the triple as the duplicate key because the
 * table's UNIQUE is composite — the same FITID with a different amount/date is a
 * distinct transaction (e.g. an original purchase vs its refund).
 */
async checkExistingTxKeys(accountId: number, keys: TxKey[]) : Promise<Result<TxKey[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_existing_tx_keys", { accountId, keys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The month's largest expenses (or all-time when `month` is None).
 * Filters: amount < 0, category `kind != 'transfer'` (excludes bill payments,
 * internal transfers and investment deposits). Ordered most to least expensive
 * (CAST AS REAL ASC, since amounts are negative).
 */
async topExpenses(month: string | null, limit: number | null) : Promise<Result<ExpenseRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("top_expenses", { month, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransactionCategory(transactionId: number, categoryId: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction_category", { transactionId, categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransactionNotes(transactionId: number, notes: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction_notes", { transactionId, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRules() : Promise<Result<Rule[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Like `list_rules` but with each rule's reach. A separate command because
 * the count scans transactions — callers that only need the rules (import,
 * suggestions, calendar) should not pay for it.
 */
async listRulesWithCount() : Promise<Result<RuleWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rules_with_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRule(input: NewRule) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRule(ruleId: number, input: UpdateRule) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_rule", { ruleId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRule(ruleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a rule AND clears category_id from any transaction that was likely
 * categorized BY this rule (description matches ANY of its patterns +
 * category_id is this rule's category). Then re-applies remaining rules to
 * pick alternatives.
 * 
 * Used by the import screen when the user wants to undo an auto-created rule.
 * Returns the count of transactions whose category was cleared.
 */
async deleteRuleWithCleanup(ruleId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule_with_cleanup", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run all rules on transactions with `category_id IS NULL` (manual categorization
 * is never overwritten). When multiple rules match the same transaction, the one
 * with the highest priority wins; ties broken by most recent created_at.
 * Returns the count of transactions newly categorized.
 */
async applyRulesToUncategorized(accountId: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_rules_to_uncategorized", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The transactions a rule reaches, newest first.
 * 
 * Uses the SAME `EXISTS` over `rule_patterns` as the count in
 * `list_rules_with_count`: the number the table shows promises what this list
 * contains, and the two diverging would be a silent lie.
 */
async transactionsMatchingRule(ruleId: number) : Promise<Result<RuleMatches, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transactions_matching_rule", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Everything applying the rules WOULD change, without writing anything.
 * 
 * Unlike `apply_rules_to_uncategorized`, which only touches uncategorized
 * rows, this also includes transactions that already have a category whose
 * winning rule points elsewhere — the ones the review screen must show before
 * overwriting anything.
 * 
 * Transactions where the winning rule already agrees with the current category
 * are left out: they are not changes, and listing them would only make the
 * review look bigger than it is.
 */
async previewRuleApplication(accountId: number | null) : Promise<Result<RulePreviewRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_rule_application", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes only the changes the user ticked in the review.
 * 
 * Takes the target category along rather than re-querying the rules: what gets
 * written is exactly what was shown, even if a rule changed meanwhile.
 */
async applyRuleChoices(choices: RuleChoice[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_rule_choices", { choices }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Crosses rules with the month's transactions to build calendar events.
 * 
 * Per rule:
 * - `due_day` set: emits an event with the due date, even with no match
 * - a matching transaction in the month: enriches it with paid_day,
 * paid_amount and paid_transaction_id
 * - `due_day` NULL and no match: the rule does NOT appear ("only shows when
 * paid", which is the user's mental model)
 * 
 * With several matches in the same month, the earliest one wins.
 */
async calendarEvents(month: string) : Promise<Result<CalendarEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_events", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveCnpj(cnpj: string) : Promise<Result<CnpjResolution, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_cnpj", { cnpj }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns groups of uncategorized OUTFLOW transactions whose normalized key
 * repeats at least `min_count` times. Sorted by absolute total descending.
 * 
 * Only considers `amount < 0` (outflows). Inflows need no category — income is
 * tracked by counterparty in the Dashboard's income sources panel.
 */
async suggestRules(minCount: number) : Promise<Result<RuleSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_rules", { minCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Suggested pattern for a single description — same logic as the Suggestions
 * tab, exposed so a rule can be created from a transaction's detail panel.
 */
async suggestPatternFor(description: string) : Promise<string> {
    return await TAURI_INVOKE("suggest_pattern_for", { description });
},
async enrichmentStatus() : Promise<Result<EnrichmentStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enrichment_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEnrichmentEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_enrichment_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Spawns the enrichment on a thread and returns immediately.
 * 
 * It is still a synchronous `fn`, and that is correct: the body does not
 * block, it only spawns.
 */
async startCnpjEnrichment(accountId: number | null, onEvent: TAURI_CHANNEL<EnrichEvent>) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_cnpj_enrichment", { accountId, onEvent }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Requests a stop. What was already created stays — cancelling is stopping
 * work, not undoing the work done.
 */
async cancelCnpjEnrichment() : Promise<void> {
    await TAURI_INVOKE("cancel_cnpj_enrichment");
},
async summaryKpis(month: string | null) : Promise<Result<KpiSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_kpis", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summaryByCategory(month: string | null) : Promise<Result<CategorySpend[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_by_category", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summaryByMonth(monthsBack: number) : Promise<Result<MonthSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_by_month", { monthsBack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async investmentSummary(month: string | null) : Promise<Result<InvestmentSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("investment_summary", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transferSummary(month: string | null) : Promise<Result<TransferSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_summary", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Aggregates the month's inflows (`amount > 0`, kind != 'transfer') by
 * counterparty. Marks a source recurring when it also appeared in BOTH months
 * immediately before the displayed one (see `is_recurring`).
 */
async incomeSources(month: string | null) : Promise<Result<IncomeSource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("income_sources", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the absolute path of the active SQLite DB file as a string.
 */
async dbPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a file's raw bytes. Used by OFX drag-and-drop: Tauri's drop event
 * delivers only the path, not the contents.
 */
async readFileBytes(path: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_bytes", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drains the pending paths. The frontend calls this on mount and on every
 * `open-ofx` event.
 */
async takePendingOfx() : Promise<string[]> {
    return await TAURI_INVOKE("take_pending_ofx");
},
/**
 * Copy the active DB file to `destination`. Issues a WAL checkpoint first
 * so the .db file is consistent on disk before copying.
 */
async exportBackup(destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_backup", { destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate that `source` is a SQLite 3 file (header magic + size > 16),
 * then overwrite the active DB. Frontend should prompt the user to restart
 * the app after this call.
 */
async restoreBackup(source: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_backup", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSetting(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppSetting(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWatchedFolders() : Promise<Result<WatchedFolder[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_watched_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWatchedFolder(path: string) : Promise<Result<WatchedFolder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_watched_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWatchedFolderPath(id: number, path: string) : Promise<Result<WatchedFolder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watched_folder_path", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWatchedFolder(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_watched_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a folder if missing. Exists only for the "iCloud Drive › finan"
 * preset, the feature's only disk write, and even then only after explicit
 * confirmation in the UI.
 * 
 * Three lines here avoid pulling in the whole `tauri-plugin-fs`, which would
 * open far more file access than needed.
 */
async ensureDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lets the UI ask "create the folder?" only when it really is missing.
 */
async dirExists(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("dir_exists", { path });
},
/**
 * The scan runs on window focus — exactly when the user is coming back to
 * interact. So the DB mutex is taken in two short moments (read the folders /
 * write the result) and **released** during disk work: holding it end to end
 * would freeze the whole UI, which shares that same mutex.
 */
async scanWatchedFolders() : Promise<Result<DiscoveredFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_watched_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markFile(contentHash: string, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_file", { contentHash, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLocales() : Promise<LocaleInfo[]> {
    return await TAURI_INVOKE("list_locales");
},
async getActiveLocale() : Promise<string> {
    return await TAURI_INVOKE("get_active_locale");
},
async setActiveLocale(code: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_locale", { code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Account = { id: number; name: string; bank: string | null; ofx_acctid: string | null; 
/**
 * `"checking"` or `"credit_card"`. Drives how the app displays and
 * categorizes transactions from this account.
 */
kind: string; created_at: string }
export type AutoClassifyReport = { created_rules: Rule[]; txs_classified: number; unresolved: CnpjResolution[] }
/**
 * A calendar event: a rule plus an optional due day plus an optional matching
 * transaction.
 */
export type CalendarEvent = { rule_id: number; 
/**
 * The snippet that actually matched — or the rule's first one, when the
 * event exists only because of `due_day` and nothing matched yet.
 */
pattern: string; category_name: string; category_color_token: string | null; due_day: number | null; paid_day: number | null; paid_amount: string | null; paid_transaction_id: number | null }
export type Category = { id: number; name: string; color_token: string | null; kind: string; is_investment: boolean; created_at: string }
export type CategorySpend = { category_id: number | null; name: string; color_token: string | null; total: string; percent: number }
export type CategoryWithCount = { id: number; name: string; color_token: string | null; kind: string; created_at: string; transaction_count: number }
/**
 * Brazilian field names on purpose: this is the UI contract, not the core.
 */
export type CnpjResolution = { cnpj: string; razao_social: string | null; nome_fantasia: string | null; cnae_fiscal: string | null; cnae_fiscal_descricao: string | null; suggested_category_id: number | null }
export type DiscoveredFile = { id: number; content_hash: string; path: string; file_name: string; size: number; status: string; seen_at: string }
/**
 * What the background thread tells the interface, in order.
 * 
 * `Started` carries the denominator — that is what buys the determinate bar
 * the HIG prefers, with no invented estimate, because the list of unique tax
 * ids is known before the first lookup.
 * 
 * `Failed` and `Aborted` are failures of different natures and the interface
 * needs to tell them apart: a lookup that went wrong inside a loop that keeps
 * going is not the work having died.
 */
export type EnrichEvent = { kind: "Started"; total: number } | { kind: "Resolved"; done: number; label: string; rule: Rule } | { kind: "Unresolved"; done: number; resolution: CnpjResolution } | { kind: "Failed"; done: number; tax_id: string } | { kind: "Finished"; report: AutoClassifyReport } | { kind: "Cancelled"; report: AutoClassifyReport } | { kind: "Aborted"; message: string }
export type EnrichmentStatus = { 
/**
 * Active locale has a tax-id format and a known provider. When `false`
 * the UI hides the setting instead of showing an inert switch.
 */
available: boolean; enabled: boolean; 
/**
 * e.g. "CNPJ" — so the screen names the id the way the user knows it.
 */
tax_id_name: string; 
/**
 * e.g. "brasilapi" — shown before opting in, so the user knows who is
 * being called.
 */
provider: string }
/**
 * A row in the "largest expenses" widget — a transaction with its category
 * resolved inline (name plus colour token) to avoid a second round-trip.
 */
export type ExpenseRow = { id: number; date: string; amount: string; description: string; category_id: number | null; category_name: string | null; category_color_token: string | null }
export type HealthInfo = { version: string; db_path: string; category_count: number }
/**
 * An aggregated income source (someone who pays you). Replaces the idea of an
 * "income category" — for inflows what matters is **who paid**.
 */
export type IncomeSource = { 
/**
 * Stable grouping key (tax id, masked personal id, or name).
 */
key: string; 
/**
 * Readable label for the UI.
 */
label: string; 
/**
 * Total received from this source in the month.
 */
total: string; 
/**
 * How many tx from this source in the month.
 */
count: number; 
/**
 * Share of the month's total inflows.
 */
percent: number; 
/**
 * True when this source appeared in >= 2 distinct months of history.
 */
is_recurring: boolean; 
/**
 * How many distinct months this source appeared in, all-time.
 */
recurring_months: number }
export type InsertResult = { inserted: number; skipped_duplicates: number; auto_categorized: number }
/**
 * Everything about categories with kind='transfer' AND is_investment=1.
 * `saldo_acumulado` sums (deposited - withdrawn) over the WHOLE history in the
 * DB, not just the month. It is net capital put in, excluding returns, which
 * OFX does not carry.
 */
export type InvestmentSummary = { aplicado_no_mes: string; resgatado_no_mes: string; aplicacoes_count: number; resgates_count: number; saldo_acumulado: string }
export type KpiSummary = { income: string; expense: string; net: string; transaction_count: number }
export type LocaleInfo = { code: string; name: string; flag: string }
export type MonthSummary = { month: string; income: string; expense: string }
export type NewAccount = { name: string; bank: string | null; ofx_acctid: string | null; 
/**
 * Defaults to `"checking"` when the frontend omits it (back-compat).
 */
kind?: string }
export type NewCategory = { name: string; color_token: string | null; kind: string }
export type NewRule = { patterns: string[]; category_id: number; priority: number; due_day: number | null; display_name?: string | null }
export type NewTransaction = { date: string; 
/**
 * Decimal as string. Backend converts via rust_decimal.
 */
amount: string; description: string; ofx_fitid: string | null }
export type Rule = { id: number; 
/**
 * Snippets searched in the description, OR'd: the rule matches when the
 * description contains ANY of them. Never empty.
 */
patterns: string[]; category_id: number; priority: number; 
/**
 * Day of month (1-31) the bill is due. NULL means no due date — the rule
 * only shows on the calendar when it matches a transaction.
 */
due_day: number | null; 
/**
 * Friendly label (e.g. legal name from a CNPJ lookup). NULL means none,
 * and the UI falls back to the first pattern.
 */
display_name: string | null; created_at: string }
/**
 * A user's choice on the review screen: this transaction goes to this
 * category.
 * 
 * The category is explicit rather than recomputed at apply time — if rules
 * change between review and click, what was reviewed is what gets written.
 */
export type RuleChoice = { transaction_id: number; category_id: number }
/**
 * The transactions a rule reaches, plus their total.
 * 
 * "Reach" is the same criterion as the count in [`RuleWithCount`], and the two
 * MUST agree — the number in the table is what promises this list's contents.
 */
export type RuleMatches = { transactions: Transaction[]; 
/**
 * Sum of the amounts, added with `rust_decimal` — never f64, which would
 * accumulate error over a long list.
 */
total: string }
/**
 * A change applying the rules would cause. Material for the review screen —
 * nothing is written until the user chooses.
 */
export type RulePreviewRow = { transaction_id: number; date: string; 
/**
 * Decimal as string, like everywhere else. Never f64.
 */
amount: string; description: string; 
/**
 * `None` means uncategorized. Anything else means applying the rule
 * REPLACES the current category.
 * 
 * Note: the DB does not record who set the category, so this cannot tell
 * "the user picked it" from "an earlier rule set it". The UI must not
 * claim authorship — only that a category exists and would change.
 */
current_category_id: number | null; new_category_id: number; rule_id: number; 
/**
 * Label of the winning rule: `display_name` when set, otherwise the
 * snippet that actually matched this description.
 */
rule_label: string }
export type RuleSuggestion = { key: string; label: string; suggested_pattern: string; count: number; total: string; sample_description: string; transaction_ids: number[] }
/**
 * A rule plus how many transactions it reaches — for the Rules screen, where
 * the question is "is this rule catching anything?".
 */
export type RuleWithCount = { id: number; patterns: string[]; category_id: number; priority: number; due_day: number | null; display_name: string | null; created_at: string; 
/**
 * Transactions whose description matches ANY of the rule's snippets,
 * regardless of their current category. This is reach, not authorship: a
 * manually categorized transaction still counts, and so does one a
 * higher-priority rule took.
 */
transaction_count: number }
export type TAURI_CHANNEL<TSend> = null
export type Transaction = { id: number; account_id: number; date: string; 
/**
 * Decimal serialized as string (e.g. "-123.45"). Never f64.
 */
amount: string; description: string; category_id: number | null; notes: string | null; ofx_fitid: string | null; imported_at: string }
export type TransactionFilters = { account_id: number | null; month: string | null; category_id: number | null; q: string | null; limit: number | null }
/**
 * Breakdown of internal transfers (kind='transfer' AND is_investment=0)
 * — card bill payments, self-transfers, etc. Gives the Dashboard a way to be
 * transparent about what was excluded from the KPIs.
 */
export type TransferSummary = { total_out: string; total_in: string; count: number }
/**
 * Triple used to dedupe against the composite UNIQUE
 * `(account_id, ofx_fitid, date, amount)` from the `transactions` table.
 */
export type TxKey = { ofx_fitid: string; date: string; amount: string }
export type UpdateCategory = { name: string; color_token: string | null; kind: string }
export type UpdateRule = { patterns: string[]; category_id: number; priority: number; due_day: number | null; display_name?: string | null }
export type WatchedFolder = { id: number; path: string; 
/**
 * Short display name ("finan", "Downloads"), derived from the last path
 * component when the folder was added.
 */
label: string; 
/**
 * `false` when the folder is gone or unmounted — the row shows an error
 * state but the other folders keep working.
 */
exists: boolean; imported_count: number; last_imported_at: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
