// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async healthCheck() : Promise<Result<HealthInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("health_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listAccounts() : Promise<Result<Account[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns existing account matching `ofx_acctid` if any, otherwise creates one.
 * `kind` é preservado quando a conta já existe (não sobrescreve).
 */
async createOrGetAccount(input: NewAccount) : Promise<Result<Account, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_or_get_account", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategories() : Promise<Result<Category[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listCategoriesWithCount() : Promise<Result<CategoryWithCount[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_categories_with_count") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createCategory(input: NewCategory) : Promise<Result<Category, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_category", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCategory(categoryId: number, input: UpdateCategory) : Promise<Result<Category, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { categoryId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Apaga uma categoria. Transações que a referenciavam ficam com category_id=NULL.
 */
async deleteCategory(categoryId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listTransactions(filters: TransactionFilters | null) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_transactions", { filters }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Insert a batch of new transactions. Returns counts of inserted vs skipped (duplicates).
 * Dedup happens via UNIQUE(account_id, ofx_fitid, date, amount) + INSERT OR IGNORE.
 * A tripla casa transações realmente idênticas — mesmo FITID com valor ou data
 * diferentes (caso típico do Nubank: compra original + estorno) entra como tx
 * distinta.
 */
async insertTransactions(accountId: number, txs: NewTransaction[]) : Promise<Result<InsertResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_transactions", { accountId, txs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dado uma lista de triplas `(fitid, date, amount)`, devolve o subconjunto que
 * já existe nessa conta. O FE usa a tripla como chave de "duplicada" porque a
 * UNIQUE da tabela é composta — mesmo FITID com valor/data diferentes é uma
 * transação distinta (e.g., compra original vs estorno).
 */
async checkExistingTxKeys(accountId: number, keys: TxKey[]) : Promise<Result<TxKey[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_existing_tx_keys", { accountId, keys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Maiores gastos do mês (ou de todo o histórico, se `month` for None).
 * Filtros: amount < 0 (saídas), categoria com `kind != 'transfer'` (exclui
 * pagamento de fatura, transferências internas, aplicações em investimento).
 * Ordem: do mais caro pro mais barato (CAST AS REAL ASC porque amounts são
 * negativos — quanto menor o número, maior o gasto).
 */
async topExpenses(month: string | null, limit: number | null) : Promise<Result<ExpenseRow[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("top_expenses", { month, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransactionCategory(transactionId: number, categoryId: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction_category", { transactionId, categoryId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTransactionNotes(transactionId: number, notes: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction_notes", { transactionId, notes }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listRules() : Promise<Result<Rule[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_rules") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createRule(input: NewRule) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_rule", { input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRule(ruleId: number, input: UpdateRule) : Promise<Result<Rule, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_rule", { ruleId, input }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRule(ruleId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a rule AND clears category_id from any transaction that was likely
 * categorized BY this rule (description matches the pattern + category_id is
 * this rule's category). Then re-applies remaining rules to pick alternatives.
 * 
 * Used by the import screen when the user wants to undo an auto-created rule.
 * Returns the count of transactions whose category was cleared.
 */
async deleteRuleWithCleanup(ruleId: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rule_with_cleanup", { ruleId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run all rules on transactions with `category_id IS NULL` (manual categorization
 * is never overwritten). When multiple rules match the same transaction, the one
 * with the highest priority wins; ties broken by most recent created_at.
 * Returns the count of transactions newly categorized.
 */
async applyRulesToUncategorized(accountId: number | null) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_rules_to_uncategorized", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cruza regras × transações do mês pra montar eventos do calendário.
 * 
 * Para cada regra:
 * - Se `due_day` set: gera evento com vencimento (mesmo sem casar transação)
 * - Se houver transação no mês cujo description casa o pattern: enriquece
 * o evento com paid_day + paid_amount + paid_transaction_id
 * - Se due_day=NULL e sem match: regra NÃO aparece (semântica do usuário:
 * "só aparece quando paga")
 * 
 * Quando múltiplas transações casam a mesma regra no mesmo mês, pega a
 * primeira (data ascendente).
 */
async calendarEvents(month: string) : Promise<Result<CalendarEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calendar_events", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveCnpj(cnpj: string) : Promise<Result<CnpjResolution, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_cnpj", { cnpj }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns groups of uncategorized OUTFLOW transactions whose normalized key
 * repeats at least `min_count` times. Sorted by absolute total descending.
 * 
 * **Importante**: só considera tx com `amount < 0` (saídas). Entradas não
 * precisam de categoria — renda é rastreada por contraparte no painel
 * "Fontes de Renda" do Dashboard.
 */
async suggestRules(minCount: number) : Promise<Result<RuleSuggestion[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suggest_rules", { minCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pattern sugerido (LIKE substring) pra uma única descrição — mesma lógica
 * da aba de Sugestões, exposta pra criar uma regra direto do painel de detalhe
 * de uma transação.
 */
async suggestPatternFor(description: string) : Promise<string> {
    return await TAURI_INVOKE("suggest_pattern_for", { description });
},
/**
 * For every uncategorized OUTFLOW transaction with a CNPJ in its description:
 * 1. Skip if a rule already exists with that CNPJ as pattern.
 * 2. Else call BrasilAPI once.
 * 3. If CNAE maps to a category → create rule (priority 10) and apply.
 * 4. Else collect into `unresolved` for the UI to handle manually.
 * 
 * **Importante**: só considera tx com `amount < 0` (saídas). Categorizar entradas
 * (salário/freela vindos de um CNPJ) não faz sentido — entradas são rastreadas
 * por contraparte no painel "Fontes de Renda", não por categoria.
 */
async autoClassifyWithCnpj(accountId: number | null) : Promise<Result<AutoClassifyReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_classify_with_cnpj", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summaryKpis(month: string | null) : Promise<Result<KpiSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_kpis", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summaryByCategory(month: string | null) : Promise<Result<CategorySpend[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_by_category", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async summaryByMonth(monthsBack: number) : Promise<Result<MonthSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("summary_by_month", { monthsBack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async investmentSummary(month: string | null) : Promise<Result<InvestmentSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("investment_summary", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async transferSummary(month: string | null) : Promise<Result<TransferSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transfer_summary", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Agrega entradas (`amount > 0`, kind != 'transfer') do mês por contraparte.
 * Marca como recorrente quando a fonte também apareceu nos DOIS meses
 * imediatamente anteriores ao mês exibido (ver `is_recurring`).
 */
async incomeSources(month: string | null) : Promise<Result<IncomeSource[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("income_sources", { month }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the absolute path of the active SQLite DB file as a string.
 */
async dbPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lê os bytes crus de um arquivo do disco. Usado pelo drag-and-drop de OFX:
 * o evento de drop do Tauri entrega só o caminho, não o conteúdo do arquivo.
 */
async readFileBytes(path: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_bytes", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Drena (retorna e limpa) os caminhos pendentes. O frontend chama isso ao
 * montar e a cada evento `open-ofx`.
 */
async takePendingOfx() : Promise<string[]> {
    return await TAURI_INVOKE("take_pending_ofx");
},
/**
 * Copy the active DB file to `destination`. Issues a WAL checkpoint first
 * so the .db file is consistent on disk before copying.
 */
async exportBackup(destination: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_backup", { destination }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Validate that `source` is a SQLite 3 file (header magic + size > 16),
 * then overwrite the active DB. Frontend should prompt the user to restart
 * the app after this call.
 */
async restoreBackup(source: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_backup", { source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSetting(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAppSetting(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_app_setting", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listWatchedFolders() : Promise<Result<WatchedFolder[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_watched_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addWatchedFolder(path: string) : Promise<Result<WatchedFolder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_watched_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateWatchedFolderPath(id: number, path: string) : Promise<Result<WatchedFolder, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_watched_folder_path", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeWatchedFolder(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_watched_folder", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cria uma pasta se ela não existir. Existe só pro preset "iCloud Drive ›
 * finan", que é a ÚNICA escrita em disco da feature — e mesmo assim só roda
 * depois da confirmação explícita do usuário na UI.
 * 
 * Três linhas aqui evitam adicionar o plugin `tauri-plugin-fs` inteiro
 * (que abriria acesso a arquivo muito além do necessário).
 */
async ensureDir(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ensure_dir", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Permite à UI perguntar "criar a pasta?" apenas quando ela realmente não
 * existe, em vez de perguntar sempre.
 */
async dirExists(path: string) : Promise<boolean> {
    return await TAURI_INVOKE("dir_exists", { path });
},
async scanWatchedFolders() : Promise<Result<DiscoveredFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("scan_watched_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listPendingFiles() : Promise<Result<DiscoveredFile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_pending_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markFile(contentHash: string, status: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_file", { contentHash, status }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listLocales() : Promise<LocaleInfo[]> {
    return await TAURI_INVOKE("list_locales");
},
async getActiveLocale() : Promise<string> {
    return await TAURI_INVOKE("get_active_locale");
},
async setActiveLocale(code: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_locale", { code }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type Account = { id: number; name: string; bank: string | null; ofx_acctid: string | null; 
/**
 * `"checking"` (conta corrente) ou `"credit_card"` (cartão de crédito).
 * Distingue como o app exibe e categoriza tx originárias dessa conta.
 */
kind: string; created_at: string }
export type AutoClassifyReport = { created_rules: Rule[]; txs_classified: number; unresolved: CnpjResolution[] }
/**
 * Evento que aparece no calendário: combinação de uma regra
 * + (opcional) dia de vencimento + (opcional) transação que casou.
 */
export type CalendarEvent = { rule_id: number; pattern: string; category_name: string; category_color_token: string | null; due_day: number | null; paid_day: number | null; paid_amount: string | null; paid_transaction_id: number | null }
export type Category = { id: number; name: string; color_token: string | null; kind: string; is_investment: boolean; created_at: string }
export type CategorySpend = { category_id: number | null; name: string; color_token: string | null; total: string; percent: number }
export type CategoryWithCount = { id: number; name: string; color_token: string | null; kind: string; created_at: string; transaction_count: number }
export type CnpjResolution = { cnpj: string; razao_social: string | null; nome_fantasia: string | null; cnae_fiscal: string | null; cnae_fiscal_descricao: string | null; suggested_category_id: number | null }
export type DiscoveredFile = { id: number; content_hash: string; path: string; file_name: string; size: number; status: string; seen_at: string }
/**
 * Linha do widget "Maiores gastos do mês" — transação com categoria
 * resolvida inline (nome + token de cor) pra evitar segundo round-trip.
 */
export type ExpenseRow = { id: number; date: string; amount: string; description: string; category_id: number | null; category_name: string | null; category_color_token: string | null }
export type HealthInfo = { version: string; db_path: string; category_count: number }
/**
 * Fonte de renda agregada (alguém que te paga). Substitui a ideia de
 * "categoria de renda" — pra entradas, o que importa é **quem pagou**.
 */
export type IncomeSource = { 
/**
 * Chave estável de agrupamento (CNPJ, CPF mascarado ou nome).
 */
key: string; 
/**
 * Rótulo legível pra UI.
 */
label: string; 
/**
 * Total recebido desta fonte no mês.
 */
total: string; 
/**
 * Quantas tx desta fonte no mês.
 */
count: number; 
/**
 * % do total de entradas do mês.
 */
percent: number; 
/**
 * True se esta fonte apareceu em ≥2 meses distintos no histórico.
 */
is_recurring: boolean; 
/**
 * Quantos meses distintos esta fonte apareceu no histórico (all-time).
 */
recurring_months: number }
export type InsertResult = { inserted: number; skipped_duplicates: number; auto_categorized: number }
/**
 * Tudo relativo a categorias com kind='transfer' AND is_investment=1.
 * `saldo_acumulado` = soma de (aplicado - resgatado) ao longo de TODO o histórico
 * disponível na DB (não apenas o mês). Representa o capital líquido que entrou
 * no investimento, sem considerar rendimentos (que a OFX não traz).
 */
export type InvestmentSummary = { aplicado_no_mes: string; resgatado_no_mes: string; aplicacoes_count: number; resgates_count: number; saldo_acumulado: string }
export type KpiSummary = { income: string; expense: string; net: string; transaction_count: number }
export type LocaleInfo = { code: string; name: string; flag: string }
export type MonthSummary = { month: string; income: string; expense: string }
export type NewAccount = { name: string; bank: string | null; ofx_acctid: string | null; 
/**
 * Default `"checking"` quando o frontend não enviar (compat retroativa).
 */
kind?: string }
export type NewCategory = { name: string; color_token: string | null; kind: string }
export type NewRule = { pattern: string; category_id: number; priority: number; due_day: number | null; display_name?: string | null }
export type NewTransaction = { date: string; 
/**
 * Decimal as string. Backend converts via rust_decimal.
 */
amount: string; description: string; ofx_fitid: string | null }
export type Rule = { id: number; pattern: string; category_id: number; priority: number; 
/**
 * Dia do mês (1-31) em que a obrigação vence. NULL = sem prazo —
 * a regra só aparece no calendário quando casa com uma transação.
 */
due_day: number | null; 
/**
 * Rótulo amigável da regra (ex: razão social vinda do CNPJ). NULL
 * = nenhum rótulo definido; a UI cai pra `pattern`.
 */
display_name: string | null; created_at: string }
export type RuleSuggestion = { key: string; label: string; suggested_pattern: string; count: number; total: string; sample_description: string; transaction_ids: number[] }
export type Transaction = { id: number; account_id: number; date: string; 
/**
 * Decimal serialized as string (e.g. "-123.45"). Never f64.
 */
amount: string; description: string; category_id: number | null; notes: string | null; ofx_fitid: string | null; imported_at: string }
export type TransactionFilters = { account_id: number | null; month: string | null; category_id: number | null; q: string | null; limit: number | null }
/**
 * Breakdown de transferências internas (kind='transfer' AND is_investment=0)
 * — pagamento de fatura, autotransferências, etc. Serve pra dar transparência
 * no Dashboard sobre o que foi excluído dos KPIs.
 */
export type TransferSummary = { total_out: string; total_in: string; count: number }
/**
 * Tripla usada pra dedup contra a UNIQUE composta
 * `(account_id, ofx_fitid, date, amount)` da tabela `transactions`.
 */
export type TxKey = { ofx_fitid: string; date: string; amount: string }
export type UpdateCategory = { name: string; color_token: string | null; kind: string }
export type UpdateRule = { pattern: string; category_id: number; priority: number; due_day: number | null; display_name?: string | null }
export type WatchedFolder = { id: number; path: string; 
/**
 * Nome curto pra exibir ("finan", "Downloads"). Derivado do último
 * componente do caminho no momento em que a pasta foi adicionada.
 */
label: string; 
/**
 * `false` quando a pasta sumiu ou foi desmontada — a linha vira estado de
 * erro na UI, mas as outras pastas seguem funcionando.
 */
exists: boolean; imported_count: number; last_imported_at: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
